version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - probo-network
    ports:
      - "6379:6379"

  api-server:
    image: puneetnj/probo-api-backend:latest
    container_name: api-server
    networks:
      - probo-network
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  engine:
    image: puneetnj/probo-engine:latest
    container_name: engine
    networks:
      - probo-network
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  websocket:
    image: puneetnj/probo-websocket:latest
    container_name: websocket
    networks:
      - probo-network
    ports:
      - "3002:3002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  probo-network:
    name: probo-network
    driver: bridge
